export const GET_ALL_DRIVERS = "GET_ALL_DRIVERS";
export const GET_DRIVERS_BY_NAME = "GET_DRIVERS_BY_NAME";
export const GET_DRIVER_BY_ID = "GET_DRIVER_BY_ID";
export const GET_ALL_TEAMS = "GET_ALL_TEAMS";
export const FILTER_DRIVERS_BY_TEAMS = 'FILTER_DRIVERS_BY_TEAMS';